os:
  - linux
  - osx
  - windows
language: node_js
node_js:
  - "12"
  - "11"
  - "10"
  - "8"
sudo: false
install:
  - npm --version
  - npm install
script: npm test
after_success: npm run coveralls
